import bpy
import struct
import math

def write_stl_binary(filepath, mesh_objects):
    """Write binary STL file from Blender mesh objects"""
    triangles = []
    
    for obj in mesh_objects:
        mesh = obj.data
        # Apply transformation
        matrix = obj.matrix_world
        
        # Get vertices in world space
        verts = [matrix @ v.co for v in mesh.vertices]
        
        # Get triangles (loop over polygons with 3 vertices)
        for poly in mesh.polygons:
            if len(poly.vertices) >= 3:
                # Use first 3 vertices
                v1 = verts[poly.vertices[0]]
                v2 = verts[poly.vertices[1]]
                v3 = verts[poly.vertices[2]]
                
                # Calculate normal
                normal = poly.normal
                normal_world = matrix.to_3x3() @ normal
                normal_world.normalize()
                
                triangles.append((normal_world, v1, v2, v3))
    
    with open(filepath, 'wb') as f:
        # Header (80 bytes)
        header = b"Generated by Blender - QUI SI DORME Sign"
        header = header.ljust(80, b'\x00')
        f.write(header)
        
        # Number of triangles (4-byte unsigned int)
        f.write(struct.pack('<I', len(triangles)))
        
        # Write each triangle
        for normal, v1, v2, v3 in triangles:
            # Normal vector (3 floats)
            f.write(struct.pack('<fff', normal.x, normal.y, normal.z))
            # Vertex 1
            f.write(struct.pack('<fff', v1.x, v1.y, v1.z))
            # Vertex 2
            f.write(struct.pack('<fff', v2.x, v2.y, v2.z))
            # Vertex 3
            f.write(struct.pack('<fff', v3.x, v3.y, v3.z))
            # Attribute byte count (unused, set to 0)
            f.write(struct.pack('<H', 0))
    
    print(f"Binary STL written: {filepath}")
    print(f"Total triangles: {len(triangles)}")

# Get all mesh objects
mesh_objects = [obj for obj in bpy.data.objects if obj.type == 'MESH']

output_path = "/Users/daniele/Downloads/Documents/opencode/LLMWiki/qui_si_dorme_sign_professional.stl"
write_stl_binary(output_path, mesh_objects)
